import { Component, ReactNode, useEffect, useState } from 'react';
import { Pressable, StyleSheet, View } from 'react-native';
import Svg, { Circle } from 'react-native-svg';
import { useQuery } from '@tanstack/react-query';
import { useNavigation } from '@react-navigation/native';
import {
  AppButton,
  AppInput,
  ChartLegend,
  AppText,
  Card,
  ErrorView,
  LoadingView,
  MultiSeriesLineChart,
  SectionHeader,
  TrendChart,
  RefreshableScrollView,
} from '../../components';
import { activityRequest, streamHistoryRequest } from '../../api/endpoints';
import { ActivityEffort } from '../../api/types';
import { ApiError } from '../../api/client';
import { useSubject } from '../../providers/SubjectProvider';
import { useAuth } from '../../providers/AuthProvider';
import { colors, spacing } from '../../theme';
import { formatDate, formatDecimal, formatDistance, formatNumber, formatPace } from '../../utils/format';
import { useActivityGoals } from './useActivityGoals';
import { getPedometerModule, isPermissionGranted } from '../../utils/pedometer';

function formatKilometers(value?: number | null) {
  const label = formatDecimal(value ?? null, 1);
  return label === '--' ? label : `${label} km`;
}

function formatWeeklyDuration(minutes?: number | null) {
  if (minutes === null || minutes === undefined || Number.isNaN(minutes)) {
    return '--';
  }
  if (minutes >= 60) {
    const hours = Math.floor(minutes / 60);
    const remainder = Math.round(minutes % 60);
    if (!remainder) {
      return `${hours}h`;
    }
    return `${hours}h ${remainder}m`;
  }
  return `${Math.round(minutes)} min`;
}

const ACTIVITY_STREAM_WINDOW_MS = 45 * 24 * 60 * 60 * 1000;
const WEEKLY_LOAD_GOAL = 500;

const AUTO_GENERATED_PATTERNS = [
  /phone workout/i,
  /workout sync/i,
  /phone sync/i,
  /phone steps/i,
];

function isAutoGeneratedName(name: string) {
  if (!name) return false;
  return AUTO_GENERATED_PATTERNS.some((re) => re.test(name));
}

export function ActivityScreen() {
  const { subjectId } = useSubject();
  const { user } = useAuth();
  const navigation = useNavigation();
  const requestSubject = subjectId && subjectId !== user?.id ? subjectId : undefined;
  const [todayPhoneSteps, setTodayPhoneSteps] = useState<number | null>(null);

  const { data, isLoading, isError, error, refetch, isRefetching } = useQuery({
    queryKey: ['activity', requestSubject || user?.id],
    queryFn: () => activityRequest({ athleteId: requestSubject }),
    enabled: Boolean(user?.id),
  });
  const { data: distanceStreamData } = useQuery({
    queryKey: ['stream-history', 'exercise.distance', requestSubject || user?.id],
    queryFn: () =>
      streamHistoryRequest({
        metric: 'exercise.distance',
        athleteId: requestSubject,
        windowMs: ACTIVITY_STREAM_WINDOW_MS,
        maxPoints: 800,
      }),
    enabled: Boolean(user?.id),
  });
  const { data: elapsedTimeStreamData } = useQuery({
    queryKey: ['stream-history', 'exercise.elapsed_time', requestSubject || user?.id],
    queryFn: () =>
      streamHistoryRequest({
        metric: 'exercise.elapsed_time',
        athleteId: requestSubject,
        windowMs: ACTIVITY_STREAM_WINDOW_MS,
        maxPoints: 800,
      }),
    enabled: Boolean(user?.id),
  });
  const { data: trainingLoadStreamData } = useQuery({
    queryKey: ['stream-history', 'exercise.training_load', requestSubject || user?.id],
    queryFn: () =>
      streamHistoryRequest({
        metric: 'exercise.training_load',
        athleteId: requestSubject,
        windowMs: ACTIVITY_STREAM_WINDOW_MS,
        maxPoints: 800,
      }),
    enabled: Boolean(user?.id),
  });

  const { goals, isReady: goalsReady, saveGoals } = useActivityGoals();

  // Read phone steps once on mount for display only (no export)
  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const pedometer = getPedometerModule();
        if (!pedometer) return;
        if (pedometer.isAvailableAsync && !(await pedometer.isAvailableAsync())) return;
        let permission = null;
        if (pedometer.getPermissionsAsync) {
          permission = await pedometer.getPermissionsAsync();
        }
        if (!isPermissionGranted(permission) && pedometer.requestPermissionsAsync) {
          permission = await pedometer.requestPermissionsAsync();
        }
        if (!isPermissionGranted(permission) || !pedometer.getStepCountAsync) return;
        const startOfDay = new Date();
        startOfDay.setHours(0, 0, 0, 0);
        const result = await pedometer.getStepCountAsync(startOfDay, new Date());
        const steps = Number(result?.steps);
        if (!cancelled && Number.isFinite(steps)) {
          setTodayPhoneSteps(steps);
        }
      } catch {
        // best-effort
      }
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  if (isLoading && !data) {
    return <LoadingView />;
  }

  if (!data) {
    return (
      <ErrorView
        message={isError ? extractErrorMessage(error, 'Unable to load activity') : 'No activity data available.'}
        onRetry={refetch}
      />
    );
  }

  if (typeof data !== 'object') {
    return <ErrorView message="Activity response was invalid. Please try again." onRetry={refetch} />;
  }

  const summary = data.summary;
  const sessions = Array.isArray(data.sessions) ? data.sessions : [];
  const efforts = Array.isArray(data.bestEfforts)
    ? data.bestEfforts.filter((entry): entry is ActivityEffort => Boolean(entry))
    : [];
  const mileageTrend = Array.isArray(data.charts?.mileageTrend) ? data.charts.mileageTrend : [];
  const trainingLoadTrendData = Array.isArray(data.charts?.trainingLoad) ? data.charts.trainingLoad : [];

  const streamMileageTrend = buildStreamMileageTrend(
    distanceStreamData?.points || [],
    elapsedTimeStreamData?.points || []
  );
  const streamTrainingLoadTrend = buildDailyStreamTrend(
    trainingLoadStreamData?.points || [],
    (value) => value,
    (values) => values.reduce((sum, value) => sum + value, 0)
  );

  const mileageSource = streamMileageTrend.length ? streamMileageTrend : mileageTrend;
  const trainingLoadSource = streamTrainingLoadTrend.length
    ? streamTrainingLoadTrend
    : trainingLoadTrendData.map((entry) => ({
        startTime: entry.startTime,
        value: entry.trainingLoad ?? 0,
      }));

  const mileageSeries = [
    {
      id: 'distance',
      label: 'Distance (km)',
      color: colors.accent,
      data: mileageSource.map((entry) => ({
        label: formatDate(entry.startTime, 'MMM D'),
        value: entry.distanceKm ?? 0,
      })),
    },
    {
      id: 'duration',
      label: 'Duration (min)',
      color: colors.accentStrong,
      strokeDasharray: '6,4',
      data: mileageSource.map((entry) => ({
        label: formatDate(entry.startTime, 'MMM D'),
        value: entry.movingMinutes ?? 0,
      })),
    },
  ];
  const legendItems = mileageSeries
    .filter((serie) => serie.data.length)
    .map((serie) => ({ label: serie.label, color: serie.color || colors.accent }));

  const trainingTrend = trainingLoadSource.map((entry) => ({
    label: formatDate(entry.startTime, 'MMM D'),
    value: entry.value ?? 0,
  }));

  const chartSummary = buildSummaryFromCharts(mileageSource, trainingLoadSource);
  const weeklyDistanceKm = chartSummary.weeklyDistanceKm ?? summary?.weeklyDistanceKm ?? null;
  const weeklyDurationMin = chartSummary.weeklyDurationMin ?? summary?.weeklyDurationMin ?? null;
  const weeklyTrainingLoad = chartSummary.trainingLoad ?? summary?.trainingLoad ?? null;
  const averagePaceSeconds = chartSummary.avgPaceSeconds ?? summary?.avgPaceSeconds ?? null;
  const longestRunKm = chartSummary.longestRunKm ?? summary?.longestRunKm ?? null;
  const longestRunLabel = chartSummary.longestRunLabel || summary?.longestRunName || 'Awaiting sync';

  const loadPct =
    weeklyTrainingLoad && weeklyTrainingLoad > 0
      ? Math.min(Math.round((weeklyTrainingLoad / WEEKLY_LOAD_GOAL) * 100), 100)
      : 0;

  const loadBadgeColor =
    weeklyTrainingLoad == null
      ? colors.muted
      : weeklyTrainingLoad > 400
      ? colors.warning
      : weeklyTrainingLoad > 100
      ? colors.accent
      : colors.warning;
  const loadBadgeLabel =
    weeklyTrainingLoad == null
      ? 'No data'
      : weeklyTrainingLoad > 400
      ? 'High load'
      : weeklyTrainingLoad > 100
      ? 'On track'
      : 'Low activity';

  const trainingTrendIsEmpty =
    trainingTrend.length === 0 || trainingTrend.every((p) => p.value === 0);

  // Ring geometry
  const RING_SIZE = 120;
  const RING_STROKE = 10;
  const RING_RADIUS = (RING_SIZE - RING_STROKE) / 2;
  const RING_CIRCUMFERENCE = 2 * Math.PI * RING_RADIUS;
  const ringOffset = RING_CIRCUMFERENCE * (1 - loadPct / 100);

  return (
    <RefreshableScrollView
      contentContainerStyle={styles.container}
      refreshing={isRefetching}
      onRefresh={refetch}
      showsVerticalScrollIndicator={false}
    >
      {isError ? (
        <View style={styles.errorBanner}>
          <AppText style={styles.errorText}>{extractErrorMessage(error, 'Showing cached activity data.')}</AppText>
        </View>
      ) : null}

      {/* Hero: training load ring */}
      <View style={styles.heroCard}>
        <AppText style={styles.eyebrow}>TRAINING · {data.subject?.name ?? 'Athlete'}</AppText>
        <View style={styles.heroRingRow}>
          <View style={{ width: RING_SIZE, height: RING_SIZE }}>
            <Svg width={RING_SIZE} height={RING_SIZE} pointerEvents="none">
              <Circle
                stroke={colors.border}
                cx={RING_SIZE / 2}
                cy={RING_SIZE / 2}
                r={RING_RADIUS}
                strokeWidth={RING_STROKE}
                fill="transparent"
              />
              <Circle
                stroke={colors.accent}
                cx={RING_SIZE / 2}
                cy={RING_SIZE / 2}
                r={RING_RADIUS}
                strokeWidth={RING_STROKE}
                fill="transparent"
                strokeDasharray={`${RING_CIRCUMFERENCE} ${RING_CIRCUMFERENCE}`}
                strokeDashoffset={ringOffset}
                strokeLinecap="round"
                transform={`rotate(-90 ${RING_SIZE / 2} ${RING_SIZE / 2})`}
              />
            </Svg>
            <View style={styles.ringCenter}>
              <AppText style={styles.ringNumber}>{formatNumber(weeklyTrainingLoad)}</AppText>
              <AppText style={styles.ringUnit}>pts</AppText>
            </View>
          </View>
          <View style={styles.heroMeta}>
            <AppText style={styles.heroLabel}>Weekly training load</AppText>
            {loadPct > 0 ? (
              <AppText style={styles.heroSubLabel}>{loadPct}% of weekly goal</AppText>
            ) : (
              <AppText style={styles.heroSubLabel}>No sessions logged this week</AppText>
            )}
          </View>
        </View>
        <View
          style={[styles.heroBadge, { backgroundColor: `${loadBadgeColor}1a`, borderColor: `${loadBadgeColor}44` }]}
        >
          <View style={[styles.badgeDot, { backgroundColor: loadBadgeColor }]} />
          <AppText style={[styles.badgeText, { color: loadBadgeColor }]}>{loadBadgeLabel}</AppText>
        </View>
      </View>

      {/* Goals card */}
      {goalsReady ? (
        <ActivityGoalCard
          summaryDistanceKm={weeklyDistanceKm ?? 0}
          summaryDurationMin={weeklyDurationMin ?? 0}
          goals={goals}
          onSaveGoals={saveGoals}
        />
      ) : null}

      {/* 2×3 metric grid */}
      <View style={styles.metricGrid}>
        <ActivityMetric label="WEEKLY DISTANCE" value={formatKilometers(weeklyDistanceKm)} />
        <ActivityMetric label="WEEKLY DURATION" value={formatWeeklyDuration(weeklyDurationMin)} />
        <ActivityMetric
          label="AVG PACE"
          value={averagePaceSeconds ? formatPace(averagePaceSeconds) : '–'}
          sub={averagePaceSeconds ? undefined : 'Not yet recorded'}
        />
        <ActivityMetric label="LONGEST RUN" value={formatKilometers(longestRunKm)} sub={longestRunLabel ?? undefined} />
        <ActivityMetric
          label="STEPS TODAY"
          value={todayPhoneSteps !== null ? formatNumber(todayPhoneSteps) : '–'}
        />
        <ActivityMetric
          label="VO₂ MAX"
          value={summary?.vo2maxEstimate != null ? formatDecimal(summary.vo2maxEstimate, 1) : '–'}
          sub={summary?.vo2maxEstimate != null ? undefined : 'Requires heart rate data'}
        />
      </View>

      {/* Training load chart — collapsed if empty */}
      {trainingTrendIsEmpty ? (
        <View style={styles.chartEmptyRow}>
          <AppText style={styles.chartEmptyIcon}>◌</AppText>
          <AppText style={styles.chartEmptyText}>No training load recorded yet</AppText>
        </View>
      ) : (
        <View style={styles.card}>
          <AppText style={styles.eyebrow}>TREND · TRAINING LOAD</AppText>
          <AppText style={styles.cardTitle}>Training load</AppText>
          <AppText style={styles.cardSubtitle}>Recent sessions</AppText>
          <ChartErrorBoundary fallback="Training load chart is unavailable on this device.">
            <TrendChart data={trainingTrend} yLabel="Load" />
          </ChartErrorBoundary>
        </View>
      )}

      {/* Mileage vs duration */}
      <View style={styles.card}>
        <AppText style={styles.eyebrow}>CHART · VOLUME</AppText>
        <AppText style={styles.cardTitle}>Mileage vs duration</AppText>
        <AppText style={styles.cardSubtitle}>Last sessions</AppText>
        <ChartErrorBoundary fallback="Mileage chart is unavailable on this device.">
          <MultiSeriesLineChart series={mileageSeries} yLabel="Volume" tickEvery={3} />
        </ChartErrorBoundary>
        <ChartLegend items={legendItems} />
      </View>

      {/* Best efforts */}
      <View style={styles.card}>
        <AppText style={styles.eyebrow}>BEST EFFORTS</AppText>
        <AppText style={styles.cardTitle}>Personal bests</AppText>
        {efforts.length ? (
          efforts.map((effort) => (
            <View key={effort.label} style={styles.effortRow}>
              <AppText style={styles.effortLabel}>{effort.label}</AppText>
              <View style={styles.effortRight}>
                <AppText style={styles.effortValue}>{formatDistance(effort.distance || 0)}</AppText>
                <AppText style={styles.mutedText}>{formatPace(effort.paceSeconds)}</AppText>
              </View>
            </View>
          ))
        ) : (
          <AppText style={styles.mutedText}>Not enough data yet.</AppText>
        )}
      </View>

      {/* Recent sessions */}
      <View style={styles.card}>
        <View style={styles.cardTitleRow}>
          <View style={styles.recentSessionsTitle}>
            <AppText style={styles.cardTitle}>Recent Sessions</AppText>
            {sessions.length > 0 ? (
              <View style={styles.countBadge}>
                <AppText style={styles.countBadgeText}>{sessions.length}</AppText>
              </View>
            ) : null}
          </View>
          <Pressable onPress={() => navigation.navigate('Sessions' as never)} style={styles.seeAllBtn}>
            <AppText style={styles.seeAllText}>See all</AppText>
          </Pressable>
        </View>
        {sessions.length ? (
          sessions.slice(0, 3).map((session) => {
            const distanceKm = (session.distance || 0) / 1000;
            const isNoise = distanceKm < 0.5;
            const isAutoNamed = isAutoGeneratedName(session.name || '');
            return (
              <View
                key={session.id}
                style={[styles.sessionRow, isNoise && styles.sessionRowNoise]}
              >
                <View style={{ flex: 1 }}>
                  <AppText
                    style={[
                      styles.sessionName,
                      isNoise && styles.sessionNameNoise,
                      isAutoNamed && styles.sessionNameAuto,
                    ]}
                  >
                    {session.name}
                  </AppText>
                  <AppText style={styles.mutedText}>
                    {formatDate(session.startTime)} · {session.sportType}
                  </AppText>
                </View>
                <View style={styles.sessionRight}>
                  <AppText style={[styles.sessionDistance, isNoise && styles.sessionDistanceNoise]}>
                    {formatDistance(session.distance || 0)}
                  </AppText>
                  <AppText style={styles.mutedText}>{formatPace(session.averagePace)}</AppText>
                </View>
              </View>
            );
          })
        ) : (
          <AppText style={styles.mutedText}>No sessions available yet.</AppText>
        )}
      </View>
    </RefreshableScrollView>
  );
}

interface ActivityGoalCardProps {
  summaryDistanceKm: number;
  summaryDurationMin: number;
  goals: { targetDistanceKm: number; targetDurationMin: number };
  onSaveGoals: (next: { targetDistanceKm: number; targetDurationMin: number }) => void;
}

function ActivityGoalCard({ summaryDistanceKm, summaryDurationMin, goals, onSaveGoals }: ActivityGoalCardProps) {
  const [isEditing, setIsEditing] = useState(false);
  const [distanceInput, setDistanceInput] = useState(String(goals.targetDistanceKm));
  const [durationInput, setDurationInput] = useState(String(goals.targetDurationMin));
  const [message, setMessage] = useState<string | null>(null);

  useEffect(() => {
    if (isEditing) return;
    setDistanceInput(String(goals.targetDistanceKm));
    setDurationInput(String(goals.targetDurationMin));
  }, [goals.targetDistanceKm, goals.targetDurationMin, isEditing]);

  const distanceProgress = computeProgress(summaryDistanceKm, goals.targetDistanceKm);
  const durationProgress = computeProgress(summaryDurationMin, goals.targetDurationMin);

  const handleSave = () => {
    const distance = Number(distanceInput);
    const duration = Number(durationInput);
    if (!Number.isFinite(distance) || distance <= 0) {
      setMessage('Enter a positive weekly distance.');
      return;
    }
    if (!Number.isFinite(duration) || duration <= 0) {
      setMessage('Enter a positive weekly duration.');
      return;
    }
    onSaveGoals({ targetDistanceKm: distance, targetDurationMin: duration });
    setIsEditing(false);
    setMessage('Goals updated.');
  };

  const handleCancel = () => {
    setIsEditing(false);
    setMessage(null);
  };

  return (
    <Card>
      <SectionHeader
        title="Activity goals"
        subtitle="Weekly targets"
        action={
          !isEditing ? (
            <Pressable onPress={() => setIsEditing(true)} style={styles.pencilBtn} hitSlop={8}>
              <AppText style={styles.pencilIcon}>✏</AppText>
            </Pressable>
          ) : null
        }
      />
      {isEditing ? (
        <View style={styles.goalForm}>
          <AppInput
            label="Weekly distance (km)"
            value={distanceInput}
            keyboardType="numeric"
            onChangeText={setDistanceInput}
          />
          <AppInput
            label="Weekly duration (min)"
            value={durationInput}
            keyboardType="numeric"
            onChangeText={setDurationInput}
          />
          <View style={styles.goalActions}>
            <AppButton title="Save goals" onPress={handleSave} />
            <AppButton title="Cancel" variant="ghost" onPress={handleCancel} />
          </View>
          {message ? (
            <AppText variant="muted" style={styles.goalFeedback}>
              {message}
            </AppText>
          ) : null}
        </View>
      ) : (
        <View style={styles.goalContent}>
          <GoalProgressBar
            label="Distance"
            progress={distanceProgress}
            currentLabel={formatKilometers(summaryDistanceKm)}
            targetLabel={formatKilometers(goals.targetDistanceKm)}
          />
          <GoalProgressBar
            label="Duration"
            progress={durationProgress}
            currentLabel={formatWeeklyDuration(summaryDurationMin)}
            targetLabel={formatWeeklyDuration(goals.targetDurationMin)}
          />
          {message ? (
            <AppText variant="muted" style={styles.goalFeedback}>
              {message}
            </AppText>
          ) : null}
        </View>
      )}
    </Card>
  );
}

function GoalProgressBar({
  label,
  progress,
  currentLabel,
  targetLabel,
}: {
  label: string;
  progress: number;
  currentLabel: string;
  targetLabel: string;
}) {
  const cappedProgress = Math.min(100, progress);
  return (
    <View style={styles.goalMetric}>
      <View style={styles.goalMetricHeader}>
        <AppText variant="body" weight="semibold">
          {label}
        </AppText>
        <AppText variant="label">{formatPercent(progress)}</AppText>
      </View>
      <View style={styles.goalBar}>
        <View style={[styles.goalBarFill, { width: `${cappedProgress}%` }]} />
      </View>
      <AppText variant="muted">
        {currentLabel} of {targetLabel}
      </AppText>
    </View>
  );
}

function computeProgress(current: number, goal: number) {
  if (!Number.isFinite(goal) || goal <= 0) return 0;
  if (!Number.isFinite(current) || current <= 0) return 0;
  return Math.min((current / goal) * 100, 999);
}

function formatPercent(value: number) {
  return `${Math.round(Math.min(value, 999))}%`;
}

function buildSummaryFromCharts(
  mileageRows: Array<{ startTime: string; distanceKm?: number | null; movingMinutes?: number | null }>,
  trainingRows: Array<{ startTime: string; value?: number | null }>
) {
  const nowTs = Date.now();
  const windowStartTs = nowTs - 7 * 24 * 60 * 60 * 1000;
  const weeklyMileageRows = mileageRows.filter((row) => {
    const ts = Date.parse(row.startTime);
    return Number.isFinite(ts) && ts >= windowStartTs && ts <= nowTs;
  });
  const weeklyTrainingRows = trainingRows.filter((row) => {
    const ts = Date.parse(row.startTime);
    return Number.isFinite(ts) && ts >= windowStartTs && ts <= nowTs;
  });
  const weeklyDistanceKm = weeklyMileageRows.length
    ? weeklyMileageRows.reduce((sum, row) => sum + toFiniteNumberOrZero(row.distanceKm), 0)
    : null;
  const weeklyDurationMin = weeklyMileageRows.length
    ? weeklyMileageRows.reduce((sum, row) => sum + toFiniteNumberOrZero(row.movingMinutes), 0)
    : null;
  const trainingLoad = weeklyTrainingRows.length
    ? weeklyTrainingRows.reduce((sum, row) => sum + toFiniteNumberOrZero(row.value), 0)
    : null;
  const avgPaceSeconds =
    weeklyDistanceKm && weeklyDistanceKm > 0 && weeklyDurationMin && weeklyDurationMin > 0
      ? Math.round((weeklyDurationMin * 60) / weeklyDistanceKm)
      : null;

  let longestRunKm: number | null = null;
  let longestRunLabel: string | null = null;
  mileageRows.forEach((row) => {
    const distanceKm = toFiniteNumberOrZero(row.distanceKm);
    if (distanceKm <= 0) return;
    if (longestRunKm === null || distanceKm > longestRunKm) {
      longestRunKm = distanceKm;
      longestRunLabel = formatDate(row.startTime, 'MMM D');
    }
  });

  return { weeklyDistanceKm, weeklyDurationMin, trainingLoad, avgPaceSeconds, longestRunKm, longestRunLabel };
}

function toFiniteNumberOrZero(value: number | null | undefined) {
  return Number.isFinite(value) ? Number(value) : 0;
}

function normalizeDistanceKilometers(value: number) {
  if (!Number.isFinite(value)) return null;
  return value > 500 ? value / 1000 : value;
}

function buildStreamMileageTrend(
  distancePoints: Array<{ ts: number; value: number | null }>,
  elapsedTimePoints: Array<{ ts: number; value: number | null }>
) {
  const distanceTrend = buildDailyStreamTrend(
    distancePoints,
    normalizeDistanceKilometers,
    (values) => Math.max(...values)
  );
  const durationTrend = buildDailyStreamTrend(
    elapsedTimePoints,
    (value) => value / 60,
    (values) => Math.max(...values)
  );

  const rowsByDay = new Map<string, { startTime: string; distanceKm: number; movingMinutes: number }>();

  distanceTrend.forEach((entry) => {
    const row = rowsByDay.get(entry.dayKey) || { startTime: entry.startTime, distanceKm: 0, movingMinutes: 0 };
    row.startTime = row.startTime > entry.startTime ? row.startTime : entry.startTime;
    row.distanceKm = entry.value;
    rowsByDay.set(entry.dayKey, row);
  });

  durationTrend.forEach((entry) => {
    const row = rowsByDay.get(entry.dayKey) || { startTime: entry.startTime, distanceKm: 0, movingMinutes: 0 };
    row.startTime = row.startTime > entry.startTime ? row.startTime : entry.startTime;
    row.movingMinutes = entry.value;
    rowsByDay.set(entry.dayKey, row);
  });

  return Array.from(rowsByDay.values())
    .sort((a, b) => Date.parse(a.startTime) - Date.parse(b.startTime))
    .slice(-20);
}

function buildDailyStreamTrend(
  points: Array<{ ts: number; value: number | null }>,
  normalizeValue: (value: number) => number | null,
  aggregate: (values: number[]) => number
) {
  const buckets = new Map<string, { ts: number; values: number[] }>();

  points.forEach((point) => {
    if (!Number.isFinite(point?.ts) || !Number.isFinite(point?.value as number)) return;
    const normalizedValue = normalizeValue(point.value as number);
    if (!Number.isFinite(normalizedValue as number)) return;
    const ts = Math.round(point.ts);
    const date = new Date(ts);
    if (Number.isNaN(date.getTime())) return;
    const dayKey = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(
      date.getDate()
    ).padStart(2, '0')}`;
    const bucket = buckets.get(dayKey) || { ts, values: [] };
    bucket.ts = Math.max(bucket.ts, ts);
    bucket.values.push(normalizedValue as number);
    buckets.set(dayKey, bucket);
  });

  return Array.from(buckets.entries())
    .map(([dayKey, bucket]) => ({
      dayKey,
      startTime: new Date(bucket.ts).toISOString(),
      value: aggregate(bucket.values),
    }))
    .filter((entry) => Number.isFinite(entry.value))
    .sort((a, b) => Date.parse(a.startTime) - Date.parse(b.startTime));
}

function ActivityMetric({ label, value, sub }: { label: string; value: string; sub?: string }) {
  return (
    <View style={styles.activityMetric}>
      <AppText style={styles.activityMetricLabel}>{label}</AppText>
      <AppText style={styles.activityMetricValue}>{value}</AppText>
      {sub ? <AppText style={styles.mutedText}>{sub}</AppText> : null}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    padding: spacing.lg,
    gap: 12,
    paddingBottom: spacing.lg * 2,
  },
  // Hero card
  heroCard: {
    backgroundColor: colors.glass,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 20,
    gap: 12,
  },
  eyebrow: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.4,
    color: colors.muted,
    textTransform: 'uppercase',
  },
  heroRingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 20,
  },
  ringCenter: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 0,
  },
  ringNumber: {
    fontSize: 26,
    fontWeight: '700',
    color: colors.text,
    letterSpacing: -0.5,
    lineHeight: 28,
  },
  ringUnit: {
    fontSize: 11,
    color: colors.muted,
    fontWeight: '600',
  },
  heroMeta: {
    flex: 1,
    gap: 4,
  },
  heroLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.text,
    lineHeight: 20,
  },
  heroSubLabel: {
    fontSize: 13,
    color: colors.muted,
    lineHeight: 18,
  },
  heroBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    alignSelf: 'flex-start',
    borderRadius: 100,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  badgeDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  badgeText: {
    fontSize: 12,
    fontWeight: '600',
  },
  // Metric grid
  metricGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  activityMetric: {
    width: '47%',
    flexGrow: 1,
    backgroundColor: colors.panel,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 16,
    gap: 4,
  },
  activityMetricLabel: {
    fontSize: 9,
    fontWeight: '700',
    letterSpacing: 1.2,
    color: colors.muted,
    textTransform: 'uppercase',
  },
  activityMetricValue: {
    fontSize: 21,
    fontWeight: '700',
    color: colors.text,
    letterSpacing: -0.3,
  },
  // Generic card
  card: {
    backgroundColor: colors.panel,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 20,
    gap: 8,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.text,
    letterSpacing: -0.3,
  },
  cardSubtitle: {
    fontSize: 12,
    color: colors.muted,
    marginBottom: 4,
  },
  cardTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  // Training load empty state
  chartEmptyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    height: 56,
    backgroundColor: colors.panel,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 20,
  },
  chartEmptyIcon: {
    fontSize: 18,
    color: colors.muted,
    opacity: 0.5,
  },
  chartEmptyText: {
    fontSize: 13,
    color: colors.muted,
  },
  // Effort rows
  effortRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  effortLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
  },
  effortRight: {
    alignItems: 'flex-end',
    gap: 2,
  },
  effortValue: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.accent,
  },
  // Session rows
  sessionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  sessionRowNoise: {
    opacity: 0.6,
  },
  sessionName: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
  },
  sessionNameNoise: {
    fontSize: 12,
  },
  sessionNameAuto: {
    color: colors.muted,
    fontStyle: 'italic',
    fontWeight: '400',
  },
  sessionRight: {
    alignItems: 'flex-end',
    gap: 2,
  },
  sessionDistance: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.accent,
  },
  sessionDistanceNoise: {
    fontSize: 12,
  },
  recentSessionsTitle: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  countBadge: {
    backgroundColor: `${colors.muted}22`,
    borderRadius: 10,
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  countBadgeText: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.muted,
  },
  seeAllBtn: {
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  seeAllText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.accent,
  },
  // Misc
  mutedText: {
    fontSize: 13,
    color: colors.muted,
    lineHeight: 18,
  },
  errorBanner: {
    backgroundColor: `${colors.danger}18`,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: `${colors.danger}44`,
    padding: 12,
  },
  errorText: {
    fontSize: 13,
    color: colors.danger,
  },
  // Chart fallback (used by ChartErrorBoundary)
  chartFallback: {
    alignItems: 'center',
    paddingVertical: spacing.md,
  },
  // Goal card styles
  goalContent: {
    gap: spacing.md,
  },
  goalMetric: {
    gap: spacing.xs,
  },
  goalMetricHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  goalBar: {
    height: 8,
    borderRadius: 999,
    backgroundColor: colors.border,
    overflow: 'hidden',
  },
  goalBarFill: {
    backgroundColor: colors.accent,
    height: '100%',
  },
  goalActions: {
    flexDirection: 'row',
    gap: spacing.sm,
    flexWrap: 'wrap',
  },
  goalForm: {
    gap: spacing.sm,
  },
  goalFeedback: {
    marginTop: spacing.xs,
  },
  // Pencil edit button
  pencilBtn: {
    padding: 6,
  },
  pencilIcon: {
    fontSize: 16,
    color: colors.muted,
  },
});

function extractErrorMessage(error: unknown, fallback: string) {
  if (error instanceof ApiError) {
    if (error.message) return error.message;
    if (error.status) return `${fallback} (HTTP ${error.status})`;
  }
  if (error instanceof Error && error.message) return error.message;
  return fallback;
}

interface ChartErrorBoundaryProps {
  children: ReactNode;
  fallback: string;
}

interface ChartErrorBoundaryState {
  hasError: boolean;
}

class ChartErrorBoundary extends Component<ChartErrorBoundaryProps, ChartErrorBoundaryState> {
  state: ChartErrorBoundaryState = { hasError: false };

  static getDerivedStateFromError() {
    return { hasError: true };
  }

  componentDidCatch(error: unknown) {
    console.warn('Activity chart render failed', error);
  }

  render() {
    if (this.state.hasError) {
      return (
        <View style={styles.chartFallback}>
          <AppText variant="muted">{this.props.fallback}</AppText>
        </View>
      );
    }
    return this.props.children;
  }
}
