apiVersion: v1
kind: Service
metadata:
  name: lifestyle-web
  labels:
    app.kubernetes.io/name: lifestyle-web
    app.kubernetes.io/part-of: msml-lifestyle-monitor
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: lifestyle-web
  ports:
    - name: http
      port: 4000
      targetPort: http
