apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../
patches:
  - path: patch-deployment.yaml
  - path: patch-service.yaml
images:
  - name: ghcr.io/change-me/msml-lifestyle-web
    newName: lifestyle-web
    newTag: local
